add arabic layout
8VIM/8VIM pull request #339
Opened 2023-06-28 17:07 UTC by Oderjunkie

this definitely isn't _especially_ polished, can't really lie about that, but it's good enough for me and i thought i'd share it. the bigrams are probably wack though

2023-07-09 20:21 UTC, FoxMoss commented
lgtm

2023-07-12 05:53 UTC, flide commented
#344

2023-07-24 01:36 UTC, MaethorNaur requested changes
The layout is invalid: https://github.com/8VIM/8VIM/actions/runs/5639605374/job/15275073453?pr=339

2023-07-24 01:36 UTC, MaethorNaur commented on 8vim/src/main/res/raw/ar.yaml
> +              - lower_case: null
```suggestion
              - null
```

2023-07-24 01:36 UTC, MaethorNaur commented on 8vim/src/main/res/raw/ar.yaml
> +              - lower_case: null
```suggestion
```

2023-07-24 01:36 UTC, MaethorNaur commented on 8vim/src/main/res/raw/ar.yaml
> +              - lower_case: null
```suggestion
```

2023-07-24 01:36 UTC, MaethorNaur commented on 8vim/src/main/res/raw/ar.yaml
> +              - lower_case: null
```suggestion
```

2023-07-24 01:36 UTC, MaethorNaur commented on 8vim/src/main/res/raw/ar.yaml
> +              - lower_case: null
```suggestion
```

2023-07-24 01:42 UTC, MaethorNaur commented
It shouldn't be `- lower_case: null` but just `- null`.
Also, those lines are unnecessary as they are at the end of the quadrant and won't be rendered by default.

Setting `- null` can be helpful if you want to skip a position, like:

```json
left:
  - null
  - lower_case: a
  - lower_case: b
 ```

We skip the first position to render `a` and `b` at the 2nd and 3rd positions

2023-08-03 22:28 UTC, Oderjunkie reviewed
ah. i was in a hurry and Forgot to delete those oops

2023-08-04 06:53 UTC, MaethorNaur approved these changes

2023-09-12 21:00 UTC, merged